name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  test-build-job:
    runs-on: ubuntu-latest
      
    steps:
        # checking out the repository
      - uses: actions/checkout@v4
        
        # setting up .NET Core SDK
      - uses: actions/setup-dotnet@v4
        with:
          # SDK Version to use.
          dotnet-version: "8.0.x"
      
        # building the projects
      - name: Build
        run: dotnet build --configuration Release --verbosity minimal