name: Build

on:
  pull_request:
    branches: [ main, development ]

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: ./JQLBuilder
    steps:
      - uses: actions/checkout@v2
        
      - name: Backend Build and test
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x" # SDK Version to use.

      - name: Build
        working-directory: ${{env.PROJECT_FOLDER}}
        run: dotnet build --configuration Release
