name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish-job:
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: JQLBuilder.sln
    
    steps:
      # checking out the repository
      - uses: actions/checkout@v2
        
        # setting up .NET Core SDK
      - uses: actions/setup-dotnet@v1
        with:
          # SDK Version to use.
          dotnet-version: "8.0.x"
        
        # installing dependencies for all projects in the solution
      - name: Restore dependencies
        run: dotnet restore ${{env.solution-file}}

        # running tests for all projects in the solution
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Print release tag name
        run: echo "${{ github.event.release.tag_name }}."

      - name: Package
        working-directory: ./JQLBuilder
        run: dotnet pack --configuration Release --no-build --output ./artifacts /p:Version=${{ github.event.release.tag_name }}
        
      - name: Publish
        working-directory: ./JQLBuilder
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.SQLBUILDER_NUGET_API_KEY}}