name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main] 

jobs:
  unit-tests-job:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          # SDK Version to use.
          dotnet-version: "8.0.x" 

        # running tests for all projects in the solution
      - name: Test 
        run: dotnet test --verbosity minimal